
//Authentication
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_INITIATE = 'LOGIN_INITIATE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_INITIATE = 'LOGOUT_INITIATE';
export const LOGOUT = 'LOGOUT';

//Register
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_INITIATE = 'REGISTER_INITIATE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//Create MCQ
export const UPLOAD_MCQ_INITIATE = 'UPLOAD_MCQ_INITIATE';
export const UPLOAD_MCQ_START = 'UPLOAD_MCQ_START';
export const UPLOAD_MCQ_SUCCESS = 'UPLOAD_MCQ_SUCCESS';
export const UPLOAD_MCQ_FAIL = 'UPLOAD_MCQ_FAIL';
export const CREATE_MCQ_START = 'CREATE_MCQ_START';
export const CREATE_MCQ_END = 'CREATE_MCQ_END';

//Take MCQ
export const MCQ_START = 'MCQ_START';
export const MCQ_END = 'MCQ_END';
export const MCQ_FETCH_START = 'MCQ_FETCH_START';
export const MCQ_FETCH_INITIATE = 'MCQ_FETCH_INITIATE';
export const MCQ_FETCH_SUCCESS = 'MCQ_FETCH_SUCCESS';
export const MCQ_FETCH_FAIL = 'MCQ_FETCH_FAIL';

//Get MCQ info for list
export const MCQ_LIST_FETCH_INITIATE = 'MCQ_LIST_FETCH_INITIATE';
export const MCQ_LIST_FETCH_START = 'MCQ_LIST_START_FETCH';
export const MCQ_LIST_FETCH_SUCCESS = 'MCQ_LIST_FETCH_SUCCESS';
export const MCQ_LIST_FETCH_FAIL = 'MCQ_LIST_FETCH_FAIL';

//MCQ list actions
export const CLEAR_MCQ_LIST = 'CLEAR_MCQ_LIST';
export const DELETE_MCQ_FROM_STATE = 'DELETE_MCQ_FROM_STATE';
export const DELETE_MCQ_START = 'DELETE_MCQ_START';
export const DELETE_MCQ_SUCCESS = 'DELETE_MCQ_SUCCESS';
export const DELETE_MCQ_FAIL = 'DELETE_MCQ_FAIL';

//Admin
export const USER_LIST_START_FETCH = 'USER_LIST_START_FETCH';
export const USER_LIST_FETCH_SUCCESS = 'USER_LIST_FETCH_SUCCESS';
export const USER_LIST_FETCH_FAIL = 'USER_LIST_FETCH_FAIL';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_FROM_STATE = 'DELETE_USER_FROM_STATE';

//NotificationBar
export const ON_SHOW_NOTIFICATION_BAR = 'ON_SHOW_NOTIFICATION_BAR';
export const ON_HIDE_NOTIFICATION_BAR = 'ON_HIDE_NOTIFICATION_BAR';
